### ISSUE TITLE
Crashes when loading slimmed saves (game loads them fine)

### ISSUE THREAD

**Issue by akarnokd** [mcnicki2002/PlanetCrafterEditor#1]
Hey there. Promising tool! Run into some crashes with my saves.

### Stacking-Drone-Test.json

 ```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "s" is null
        at nicki0.editor.SaveLoader.splitDouble(SaveLoader.java:185)
        at nicki0.editor.SaveLoader.read(SaveLoader.java:88)
        at nicki0.editor.SaveLoader.<init>(SaveLoader.java:41)
        at nicki0.editor.Main.<init>(Main.java:76)
        at nicki0.editor.Main.start(Main.java:86)
        at nicki0.editor.Main.main(Main.java:89)
```

### Survival-1.json

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at nicki0.editor.SaveLoader.readLine(SaveLoader.java:177)
        at nicki0.editor.SaveLoader.readSection(SaveLoader.java:157)
        at nicki0.editor.SaveLoader.read(SaveLoader.java:62)
        at nicki0.editor.SaveLoader.<init>(SaveLoader.java:41)
        at nicki0.editor.Main.<init>(Main.java:76)
        at nicki0.editor.Main.start(Main.java:86)
        at nicki0.editor.Main.main(Main.java:89)       
```

----

⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️ 

[Planet Crafter.zip](https://github.com/mcnicki2002/PlanetCrafterEditor/files/10887809/Planet.Crafter.zip)

**Comment by mcnicki2002** [comment]
Thanks for reporting the issues.
Both Exceptions should be fixed in V0.3.2:
(1) Default values are loaded if values are missing; Additional (non 'vanilla') lines at the end of the file get saved as well.
(2) Bug when loading save file containing String ,"," solved. Only appears if the last character in the "text" value is a comma.
